modified proto for timetable
callmemars1/suai-bot-api-gateway pull request #7
Opened 2022-04-30 13:06 UTC by callmemars1

2022-04-30 17:24 UTC, Jarkness requested changes

2022-04-30 17:24 UTC, Jarkness commented on Domain/TimeTable/Protos/TimeTableService.proto
> +	string university = 7;
Может faculty? Университет у тебя один, это ГУАП.

2022-04-30 17:24 UTC, Jarkness commented on Domain/TimeTable/Protos/TimeTableService.proto
> +	string university = 5;
Аналогично с первым комментарием. (unversity->faculty)

2022-04-30 17:27 UTC, callmemars1 commented on Domain/TimeTable/Protos/TimeTableService.proto
> +	string university = 7;
Расчет на то, что сервис сможет обрабатывать несколько университетов

2022-04-30 17:32 UTC, Jarkness commented on Domain/TimeTable/Protos/TimeTableService.proto
> +	string university = 7;
Почему тогда это в структуре? Почему университет не может быть свойством неймспейса, который отвечает за конкретный университет? Писать это на уровне структуры - само по себе не очень. Для какого-то университета у тебя могут как и убраться поля из структуры, так и добавиться новые. А ты в одну структуру сейчас опрометчиво закладываешь такой функционал.

2022-04-30 17:43 UTC, Jarkness commented on Domain/TimeTable/Protos/TimeTableService.proto
>  	string classRoom = 4;
Почему ты решил не использовать здесь numeric формат?

2022-04-30 17:50 UTC, callmemars1 commented on Domain/TimeTable/Protos/TimeTableService.proto
>  	string classRoom = 4;
у аудиторий бывают приставки в виде букв
![image](https://user-images.githubusercontent.com/86615975/166116725-a65fae32-2913-472f-b3a5-4012613d571f.png)

2022-04-30 17:52 UTC, callmemars1 commented on Domain/TimeTable/Protos/TimeTableService.proto
>  	string classRoom = 4;
или спортзал например

2022-04-30 17:53 UTC, Jarkness commented
Не вижу типа занятия (очное-заочное).

2022-04-30 18:13 UTC, Jarkness requested changes

2022-04-30 18:13 UTC, Jarkness commented on Domain/TimeTable/Protos/TimeTableService.proto
>  	WeekDays weekDay = 5;
WeekDays в отдельный прото, как это сделано у google - https://github.com/protobuf-net/protobuf-net/blob/main/src/protogen.site/wwwroot/protoc/google/type/dayofweek.proto

В последствии он тебе еще может пригодится в других контрактах, их хорошо, если он везде будет однородным.

2022-04-30 18:13 UTC, Jarkness commented on Domain/TimeTable/Protos/TimeTableService.proto
>  	WeekDays weekDay = 5;
ENUM с типами занятий тоже в отдельный прото.

2022-04-30 18:14 UTC, Jarkness commented on Domain/TimeTable/Protos/TimeTableService.proto
>  	WeekDays weekDay = 5;
ENUM с типами недель тоже в отдельный прото.

2022-04-30 18:52 UTC, callmemars1 commented on Domain/TimeTable/Protos/TimeTableService.proto
>  	WeekDays weekDay = 5;
Сделано

2022-04-30 18:52 UTC, callmemars1 commented
> Не вижу типа занятия (очное-заочное).

Сделано

2022-04-30 18:52 UTC, callmemars1 commented on Domain/TimeTable/Protos/TimeTableService.proto
> +	string university = 7;
Исправлено

2022-04-30 18:57 UTC, Jarkness requested changes

2022-04-30 18:57 UTC, Jarkness commented on Domain/TimeTable/Protos/WeekDays.proto
> +	MONDAY = 0;
У протобафа в енаме, кажется, рекомендуется (или требуется) тип unspecfified.

2022-04-30 19:21 UTC, callmemars1 commented on Domain/TimeTable/Protos/WeekDays.proto
> +	MONDAY = 0;
Пофиксил. Префикс к значению нужен для разрешения конфликта в плюсах. Считается лучшим решением, при компиляции протобафа игнорится (ну на шарпе точно)

2022-05-01 09:09 UTC, Jarkness approved these changes

2022-05-01 11:21 UTC, merged