added proto for teacher info service
callmemars1/suai-bot-api-gateway pull request #8
Opened 2022-04-30 17:06 UTC by callmemars1

2022-04-30 17:11 UTC, Jarkness commented on Domain/TeacherInfo/Protos/TeacherInfoService.proto
> +service TeacherInfoService{
Придерживайся одного формата, либо у тебя кавычки на одной строке с началом блока, либо на следующей.

2022-04-30 17:12 UTC, callmemars1 commented on Domain/TeacherInfo/Protos/TeacherInfoService.proto
> +service TeacherInfoService{
### кк

2022-04-30 17:14 UTC, callmemars1 commented on Domain/TeacherInfo/Protos/TeacherInfoService.proto
> +service TeacherInfoService{
> Придерживайся одного формата, либо у тебя кавычки на одной строке с началом блока, либо на следующей.

Исправил

2022-04-30 17:14 UTC, Jarkness requested changes

2022-04-30 17:14 UTC, Jarkness commented on Controllers/TimeTableController.cs
> +    public IActionResult GetTimeTable(string? university, string? group, string? teacher, string? building, string? classRoom)
В отдельную структуру все эти аргументы. Не больше 3 аргументов на функцию старайся делать. Тем более, что они у тебя все логически объединены.

2022-04-30 17:15 UTC, callmemars1 commented on Controllers/TimeTableController.cs
> +    public IActionResult GetTimeTable(string? university, string? group, string? teacher, string? building, string? classRoom)
Это будет в следующей таске
Добавил чтоб не забыть

2022-04-30 17:35 UTC, Jarkness commented on Controllers/TimeTableController.cs
> +    public IActionResult GetTimeTable(string? university, string? group, string? teacher, string? building, string? classRoom)
Напиши тогда над методом (либо местом, где такие странные сигнатуры требуются) TODO в коде.

2022-04-30 17:57 UTC, Jarkness requested changes

2022-04-30 17:57 UTC, Jarkness commented on Domain/TeacherInfo/Protos/TeacherInfoService.proto
> +	string university = 2;
После обсуждения, было решено убрать поле university из всех контрактов.
Здесь, кстати, хороший пример - у одного преподавателя может быть несколько университетов.

2022-04-30 17:59 UTC, callmemars1 commented on Controllers/TimeTableController.cs
> +    public IActionResult GetTimeTable(string? university, string? group, string? teacher, string? building, string? classRoom)
Исправил

2022-04-30 18:06 UTC, callmemars1 commented on Domain/TeacherInfo/Protos/TeacherInfoService.proto
> +	string university = 2;
Здесь я тоже убрал из контракта

2022-04-30 18:06 UTC, Jarkness commented on Controllers/TimeTableController.cs
> +    public IActionResult GetTimeTable(string? university, string? group, string? teacher, string? building, string? classRoom)
Так прям щас его оттуда и выкидывай.

2022-04-30 18:19 UTC, Jarkness requested changes

2022-04-30 18:19 UTC, Jarkness commented on Domain/TeacherInfo/Protos/TeacherInfoService.proto
> +	string academicDegree = 6;
Может быть enum в отдельном proto файле.

2022-04-30 18:23 UTC, Jarkness commented on Controllers/TimeTableController.cs
> +    public IActionResult GetTimeTable(string? university, string? group, string? teacher, string? building, string? classRoom)
После обсуждения с @callmemars1 было решено сделать это в следующей задаче (#4)

2022-04-30 18:34 UTC, callmemars1 commented on Domain/TeacherInfo/Protos/TeacherInfoService.proto
> +	string academicDegree = 6;
Что именно

2022-04-30 18:55 UTC, Jarkness commented on Domain/TeacherInfo/Protos/TeacherInfoService.proto
> +	string academicDegree = 6;
academicDegree. Комментарии к ревью указывают на ту строку, под которой стоят.

2022-04-30 18:58 UTC, callmemars1 commented on Domain/TeacherInfo/Protos/TeacherInfoService.proto
> +	string academicDegree = 6;
Мне кажется стоит оставить строкой, т.к. к степеням часто приписываются науки, в которых они получены, а их огромное множество
![image](https://user-images.githubusercontent.com/86615975/166119063-6758b492-7851-4d35-a3f7-7ddcbe63371c.png)

2022-04-30 18:59 UTC, Jarkness commented on Domain/TeacherInfo/Protos/TeacherInfoService.proto
> +	string academicDegree = 6;
Может тогда стоит хранить отдельно области и степени? Степени то у нас фиксированные везде.

2022-04-30 19:13 UTC, callmemars1 commented on Domain/TeacherInfo/Protos/TeacherInfoService.proto
> +	string academicDegree = 6;
А как хранить области, просто строкой? А что насчет докторов - доцентов?
![image](https://user-images.githubusercontent.com/86615975/166119486-6a6477a3-fca2-47eb-b091-a69356f03510.png)
А если он еще и по должности доцент?

2022-04-30 19:23 UTC, callmemars1 commented on Domain/TeacherInfo/Protos/TeacherInfoService.proto
> +	string academicDegree = 6;
Возможно такое разделение имеет смысл в бд  
Но в контракте стоит оставить строку, т.к. пользователю нужна строка, а не число в любом случае

2022-04-30 22:26 UTC, callmemars1 commented on Domain/TeacherInfo/Protos/TeacherInfoService.proto
> +	string academicDegree = 6;
Вынес должность отдельно от научной степени бтв, чего только долгие проверки пул реквестов с людьми не делают........

2022-05-01 09:15 UTC, Jarkness commented on Domain/TeacherInfo/Protos/TeacherInfoService.proto
> +	string academicDegree = 6;
@callmemars1, это еще не долго) У меня на работе PR некоторые по 3-4 недели проверяются.

Ты сейчас это разнес в две строки, что еще хуже, наверно. Оставь тогда одну. Я предлагал через enum, но сейчас (после обсуждения) вижу, что это решение нам не подходит.

2022-05-01 09:30 UTC, callmemars1 commented on Domain/TeacherInfo/Protos/TeacherInfoService.proto
> +	string academicDegree = 6;
Разнёс в две,ТК существует ассистенты, и это вроде должность а не степень

2022-05-01 11:11 UTC, Jarkness approved these changes

2022-05-01 11:19 UTC, merged