Task/5/update timetable api controller
callmemars1/suai-bot-api-gateway pull request #9
Opened 2022-05-01 21:39 UTC by callmemars1

## Изменения
- Изменил аргументы, теперь они собраны в одном классе TimetableRequestArgs
- Изменил формат запроса, теперь он выглядит как 
```
https://somedomain.com/suai.timetable.get?queryString
```
- Убрал университет из параметров запроса, теперь он определяется роутингом к контроллеру
- Добавил актуальный тип недели в результат запроса
- еще изменения по мелочи

2022-05-01 22:17 UTC, Jarkness requested changes

2022-05-01 22:17 UTC, Jarkness commented on Controllers/TimeTableController.cs
> +    /// <param name="timeTableProvider">Провайдер расписания</param>
По имени класса и так ясно, что это такое. Можно просто назвать dataProvider.

2022-05-01 22:17 UTC, Jarkness commented on Models/TimeTable/ITimeTableProvider.cs
> +/// Единый интерфейс для всех классов, предоставляющих расписание
Бесполезный комментарий

2022-05-01 22:17 UTC, Jarkness commented on Models/TimeTable/GRPCTimeTableProvider.cs
> +    /// Конструктор
Бесполезный комментарий. Любой человек, программирующий на C# и без него поймет, что это конструктор.

2022-05-01 22:17 UTC, Jarkness commented on Domain/TimeTable/Exceptions/ServiceUnavailableException.cs
> +/// Ошибка, означающая, что сервис не доступен
Комментарий повторяет название ошибки. Гораздо полезнее написать, в каком случае эта ошибка возникает.

2022-05-01 22:17 UTC, Jarkness commented on Controllers/TimeTableController.cs
> +            _logger.Log(LogLevel.Warning, "Timetable service unavailable");
*is

2022-05-01 22:17 UTC, Jarkness commented on Controllers/TimeTableController.cs
> +    /// <returns>Результат запроса</returns>
Бесполезный комментарий.

2022-05-01 22:17 UTC, Jarkness commented on Domain/TimeTable/Lesson.cs
>      public string LessonName { get; set; } = string.Empty;
По имени структуры и так ясно, что это !Lesson! name. Тоже самое и с остальными полями.

2022-05-01 22:17 UTC, Jarkness commented on Models/TimeTable/GRPCTimeTableProvider.cs
> +/// </summary>
TimetableProviderFromGRPCSource. И комментарий можно убрать.

2022-05-01 22:17 UTC, Jarkness commented on Models/TimeTable/GRPCTimeTableProvider.cs
>      private readonly string _serviceAddress;
Бесполезный комментарий.

2022-05-01 22:17 UTC, Jarkness commented on Models/TimeTable/GRPCTimeTableProvider.cs
> +    // Счетчик реконектов
Бесполезный комментарий.

2022-05-01 22:17 UTC, Jarkness commented on Models/TimeTable/GRPCTimeTableProvider.cs
> +    private readonly ILogger<GRPCTimetableProvider> _logger;
Бесполезный комментарий.

2022-05-01 22:17 UTC, Jarkness commented on Models/TimeTable/GRPCTimeTableProvider.cs
> +    private TimetableProvider.TimetableProviderClient _client;
_clientToSendRPC

2022-05-01 22:17 UTC, Jarkness commented on Models/TimeTable/GRPCTimeTableProvider.cs
>          // trying to reconnect
Определись с языком комментариев.

2022-05-01 22:17 UTC, Jarkness commented on Domain/TimeTable/Protos/TimeTableService.proto
>  // empty if nothing found
Определись с языком комментариев

2022-05-02 21:47 UTC, callmemars1 commented on Controllers/TimeTableController.cs
> +[Route("suai.[controller].[action]")]
ну вообще я посидел подумал, почитал про роутинг в асп.
Я же правильно понимаю, что могу на саб доменах разные сервисы запускать да?
Тогда можно было бы сделать, как в гет блоке, например:
```
https://suai.some-domain.com/timetable.get?params
```
И на каждый отдельный вуз слушать по отдельному адресу

2022-05-04 13:24 UTC, Jarkness commented on Domain/TimeTable/TimetableServiceGrpcClient.cs
> +    private uint _reconnectCounter = 0;
Ты просто это по разным методам разнес. Надо чтобы у тебя был в принципе клиент, способный к реконнекту, отдельно от запросов.
У тебя же вскоре появится кусок для учителей, и ты будешь туда эту логику реконнектов дублировать.

2022-05-05 17:02 UTC, callmemars1 commented on Models/TimeTable/GRPCTimeTableProvider.cs
> +            // map proto lesson to domain lesson
Исправил

2022-05-05 17:02 UTC, callmemars1 commented on Models/TimeTable/GRPCTimeTableProvider.cs
>      private void Reconnect()
Вынес в GrpcClientWithReconnect

2022-05-05 17:02 UTC, callmemars1 commented on Controllers/TimeTableController.cs
> +    /// <param name="logger">Логгер</param>
Убрал коммент

2022-05-05 17:03 UTC, callmemars1 commented on Controllers/TimeTableController.cs
> +    /// <param name="timeTableProvider">Провайдер расписания</param>
Убрал коммент

2022-05-05 17:03 UTC, callmemars1 commented on Models/TimeTable/ITimeTableProvider.cs
> +/// Единый интерфейс для всех классов, предоставляющих расписание
убрал

2022-05-05 17:03 UTC, callmemars1 commented on Models/TimeTable/GRPCTimeTableProvider.cs
> +    /// Конструктор
Убрал

2022-05-05 17:03 UTC, callmemars1 commented on Controllers/TimeTableController.cs
> +            _logger.Log(LogLevel.Warning, "Timetable service unavailable");
Добавил

2022-05-05 17:03 UTC, callmemars1 commented on Controllers/TimeTableController.cs
> +    /// <returns>Результат запроса</returns>
Убрал

2022-05-05 17:04 UTC, callmemars1 commented on Domain/TimeTable/Lesson.cs
>      public string LessonName { get; set; } = string.Empty;
Исправил

2022-05-05 17:04 UTC, callmemars1 commented on Models/TimeTable/GRPCTimeTableProvider.cs
> +/// </summary>
Исправил на TimetableProviderFromGRPCService

2022-05-05 17:04 UTC, callmemars1 commented on Models/TimeTable/GRPCTimeTableProvider.cs
>      private readonly string _serviceAddress;
Убрал

2022-05-05 17:04 UTC, callmemars1 commented on Models/TimeTable/GRPCTimeTableProvider.cs
> +    private readonly ILogger<GRPCTimetableProvider> _logger;
убрал

2022-05-05 17:04 UTC, callmemars1 commented on Models/TimeTable/GRPCTimeTableProvider.cs
>          // trying to reconnect
Исправил

2022-05-05 17:04 UTC, callmemars1 commented on Domain/TimeTable/Protos/TimeTableService.proto
>  // empty if nothing found
Исправил

2022-05-05 17:05 UTC, callmemars1 commented on Domain/TimeTable/TimetableServiceGrpcClient.cs
> +    private uint _reconnectCounter = 0;
Сделал GrpcClientWithReconnect

2022-05-05 17:06 UTC, callmemars1 commented on Domain/TimeTable/LessonDto.cs
> +    public IEnumerable<string> Groups { get; set; }
Хотел отвязать логику программы от протобафа, но и так сойдет, убрал свои типы

2022-05-05 17:06 UTC, callmemars1 commented on Domain/TimeTable/LessonTypes.cs
> +public enum LessonTypes
убрал

2022-05-05 17:06 UTC, callmemars1 commented on Domain/TimeTable/WeekDays.cs
>  {
убрал

2022-05-05 17:06 UTC, callmemars1 commented on Domain/TimeTable/WeekTypes.cs
>  public enum WeekTypes
убрал

2022-05-05 17:06 UTC, callmemars1 commented on Domain/TimeTable/Exceptions/ServiceUnavailableException.cs
> +/// Возникает при следующих статусах RpcException:  Unavailable, DeadlineExceeded
Исправил

2022-05-06 07:51 UTC, Jarkness approved these changes

2022-05-06 09:13 UTC, merged